// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: flight_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateFlight
type CreateFlightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flight *Flight `protobuf:"bytes,1,opt,name=flight,proto3" json:"flight,omitempty"`
}

func (x *CreateFlightRequest) Reset() {
	*x = CreateFlightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlightRequest) ProtoMessage() {}

func (x *CreateFlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flight_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlightRequest.ProtoReflect.Descriptor instead.
func (*CreateFlightRequest) Descriptor() ([]byte, []int) {
	return file_flight_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFlightRequest) GetFlight() *Flight {
	if x != nil {
		return x.Flight
	}
	return nil
}

type CreateFlightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateFlightResponse) Reset() {
	*x = CreateFlightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlightResponse) ProtoMessage() {}

func (x *CreateFlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flight_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlightResponse.ProtoReflect.Descriptor instead.
func (*CreateFlightResponse) Descriptor() ([]byte, []int) {
	return file_flight_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFlightResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// FindFlight
type FindFlightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindFlightRequest) Reset() {
	*x = FindFlightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindFlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindFlightRequest) ProtoMessage() {}

func (x *FindFlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flight_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindFlightRequest.ProtoReflect.Descriptor instead.
func (*FindFlightRequest) Descriptor() ([]byte, []int) {
	return file_flight_service_proto_rawDescGZIP(), []int{2}
}

func (x *FindFlightRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindFlightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string  `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Flight  *Flight `protobuf:"bytes,2,opt,name=flight,proto3" json:"flight,omitempty"`
}

func (x *FindFlightResponse) Reset() {
	*x = FindFlightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindFlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindFlightResponse) ProtoMessage() {}

func (x *FindFlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flight_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindFlightResponse.ProtoReflect.Descriptor instead.
func (*FindFlightResponse) Descriptor() ([]byte, []int) {
	return file_flight_service_proto_rawDescGZIP(), []int{3}
}

func (x *FindFlightResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FindFlightResponse) GetFlight() *Flight {
	if x != nil {
		return x.Flight
	}
	return nil
}

// UpdateUser
type UpdateFlightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Flight *Flight `protobuf:"bytes,2,opt,name=flight,proto3" json:"flight,omitempty"`
}

func (x *UpdateFlightRequest) Reset() {
	*x = UpdateFlightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlightRequest) ProtoMessage() {}

func (x *UpdateFlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flight_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlightRequest.ProtoReflect.Descriptor instead.
func (*UpdateFlightRequest) Descriptor() ([]byte, []int) {
	return file_flight_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateFlightRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFlightRequest) GetFlight() *Flight {
	if x != nil {
		return x.Flight
	}
	return nil
}

type UpdateFlightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateFlightResponse) Reset() {
	*x = UpdateFlightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlightResponse) ProtoMessage() {}

func (x *UpdateFlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flight_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlightResponse.ProtoReflect.Descriptor instead.
func (*UpdateFlightResponse) Descriptor() ([]byte, []int) {
	return file_flight_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFlightResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_flight_service_proto protoreflect.FileDescriptor

var file_flight_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x72, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x14,
	0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x06, 0x66,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x72, 0x65,
	0x73, 0x74, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x06, 0x66, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x22, 0x30, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x66, 0x0a, 0x12, 0x46, 0x69,
	0x6e, 0x64, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x66, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x72, 0x65, 0x73,
	0x74, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x06, 0x66, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x22, 0x5d, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x06, 0x66, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x72, 0x65, 0x73, 0x74,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x06, 0x66, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x22, 0x30, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0xd0, 0x02, 0x0a, 0x0d, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6b, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2b, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x65, 0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x29, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x71, 0x6c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x72, 0x65,
	0x73, 0x74, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6b, 0x0a, 0x0c, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2b, 0x2e, 0x72, 0x65, 0x73, 0x74,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x72,
	0x70, 0x63, 0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x70, 0x62, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_flight_service_proto_rawDescOnce sync.Once
	file_flight_service_proto_rawDescData = file_flight_service_proto_rawDesc
)

func file_flight_service_proto_rawDescGZIP() []byte {
	file_flight_service_proto_rawDescOnce.Do(func() {
		file_flight_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_flight_service_proto_rawDescData)
	})
	return file_flight_service_proto_rawDescData
}

var file_flight_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_flight_service_proto_goTypes = []interface{}{
	(*CreateFlightRequest)(nil),  // 0: rest_grpc_graphql.grpc.CreateFlightRequest
	(*CreateFlightResponse)(nil), // 1: rest_grpc_graphql.grpc.CreateFlightResponse
	(*FindFlightRequest)(nil),    // 2: rest_grpc_graphql.grpc.FindFlightRequest
	(*FindFlightResponse)(nil),   // 3: rest_grpc_graphql.grpc.FindFlightResponse
	(*UpdateFlightRequest)(nil),  // 4: rest_grpc_graphql.grpc.UpdateFlightRequest
	(*UpdateFlightResponse)(nil), // 5: rest_grpc_graphql.grpc.UpdateFlightResponse
	(*Flight)(nil),               // 6: rest_grpc_graphql.grpc.Flight
}
var file_flight_service_proto_depIdxs = []int32{
	6, // 0: rest_grpc_graphql.grpc.CreateFlightRequest.flight:type_name -> rest_grpc_graphql.grpc.Flight
	6, // 1: rest_grpc_graphql.grpc.FindFlightResponse.flight:type_name -> rest_grpc_graphql.grpc.Flight
	6, // 2: rest_grpc_graphql.grpc.UpdateFlightRequest.flight:type_name -> rest_grpc_graphql.grpc.Flight
	0, // 3: rest_grpc_graphql.grpc.FlightService.CreateFlight:input_type -> rest_grpc_graphql.grpc.CreateFlightRequest
	2, // 4: rest_grpc_graphql.grpc.FlightService.FindFlight:input_type -> rest_grpc_graphql.grpc.FindFlightRequest
	4, // 5: rest_grpc_graphql.grpc.FlightService.UpdateFlight:input_type -> rest_grpc_graphql.grpc.UpdateFlightRequest
	1, // 6: rest_grpc_graphql.grpc.FlightService.CreateFlight:output_type -> rest_grpc_graphql.grpc.CreateFlightResponse
	3, // 7: rest_grpc_graphql.grpc.FlightService.FindFlight:output_type -> rest_grpc_graphql.grpc.FindFlightResponse
	5, // 8: rest_grpc_graphql.grpc.FlightService.UpdateFlight:output_type -> rest_grpc_graphql.grpc.UpdateFlightResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_flight_service_proto_init() }
func file_flight_service_proto_init() {
	if File_flight_service_proto != nil {
		return
	}
	file_flight_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_flight_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFlightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFlightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindFlightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindFlightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFlightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFlightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_flight_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flight_service_proto_goTypes,
		DependencyIndexes: file_flight_service_proto_depIdxs,
		MessageInfos:      file_flight_service_proto_msgTypes,
	}.Build()
	File_flight_service_proto = out.File
	file_flight_service_proto_rawDesc = nil
	file_flight_service_proto_goTypes = nil
	file_flight_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FlightServiceClient is the client API for FlightService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FlightServiceClient interface {
	CreateFlight(ctx context.Context, in *CreateFlightRequest, opts ...grpc.CallOption) (*CreateFlightResponse, error)
	FindFlight(ctx context.Context, in *FindFlightRequest, opts ...grpc.CallOption) (*FindFlightResponse, error)
	UpdateFlight(ctx context.Context, in *UpdateFlightRequest, opts ...grpc.CallOption) (*UpdateFlightResponse, error)
}

type flightServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlightServiceClient(cc grpc.ClientConnInterface) FlightServiceClient {
	return &flightServiceClient{cc}
}

func (c *flightServiceClient) CreateFlight(ctx context.Context, in *CreateFlightRequest, opts ...grpc.CallOption) (*CreateFlightResponse, error) {
	out := new(CreateFlightResponse)
	err := c.cc.Invoke(ctx, "/rest_grpc_graphql.grpc.FlightService/CreateFlight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightServiceClient) FindFlight(ctx context.Context, in *FindFlightRequest, opts ...grpc.CallOption) (*FindFlightResponse, error) {
	out := new(FindFlightResponse)
	err := c.cc.Invoke(ctx, "/rest_grpc_graphql.grpc.FlightService/FindFlight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightServiceClient) UpdateFlight(ctx context.Context, in *UpdateFlightRequest, opts ...grpc.CallOption) (*UpdateFlightResponse, error) {
	out := new(UpdateFlightResponse)
	err := c.cc.Invoke(ctx, "/rest_grpc_graphql.grpc.FlightService/UpdateFlight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlightServiceServer is the server API for FlightService service.
type FlightServiceServer interface {
	CreateFlight(context.Context, *CreateFlightRequest) (*CreateFlightResponse, error)
	FindFlight(context.Context, *FindFlightRequest) (*FindFlightResponse, error)
	UpdateFlight(context.Context, *UpdateFlightRequest) (*UpdateFlightResponse, error)
}

// UnimplementedFlightServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFlightServiceServer struct {
}

func (*UnimplementedFlightServiceServer) CreateFlight(context.Context, *CreateFlightRequest) (*CreateFlightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFlight not implemented")
}
func (*UnimplementedFlightServiceServer) FindFlight(context.Context, *FindFlightRequest) (*FindFlightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindFlight not implemented")
}
func (*UnimplementedFlightServiceServer) UpdateFlight(context.Context, *UpdateFlightRequest) (*UpdateFlightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFlight not implemented")
}

func RegisterFlightServiceServer(s *grpc.Server, srv FlightServiceServer) {
	s.RegisterService(&_FlightService_serviceDesc, srv)
}

func _FlightService_CreateFlight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFlightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightServiceServer).CreateFlight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rest_grpc_graphql.grpc.FlightService/CreateFlight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightServiceServer).CreateFlight(ctx, req.(*CreateFlightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightService_FindFlight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindFlightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightServiceServer).FindFlight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rest_grpc_graphql.grpc.FlightService/FindFlight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightServiceServer).FindFlight(ctx, req.(*FindFlightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightService_UpdateFlight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFlightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightServiceServer).UpdateFlight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rest_grpc_graphql.grpc.FlightService/UpdateFlight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightServiceServer).UpdateFlight(ctx, req.(*UpdateFlightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FlightService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rest_grpc_graphql.grpc.FlightService",
	HandlerType: (*FlightServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFlight",
			Handler:    _FlightService_CreateFlight_Handler,
		},
		{
			MethodName: "FindFlight",
			Handler:    _FlightService_FindFlight_Handler,
		},
		{
			MethodName: "UpdateFlight",
			Handler:    _FlightService_UpdateFlight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flight_service.proto",
}
